export const LOAD_COMMANDS = 'LOAD_COMMANDS';
export const USE_COMMAND = 'USE_COMMAND';

export const LOAD_CONTROLS = 'LOAD_CONTROLS';
export const LINK_COMMAND_TO_CONTROL = 'LINK_COMMAND_TO_CONTROL';

export const LOAD_PRESETS = 'LOAD_PRESETS';
export const SELECT_PRESET = 'SELECT_PRESET';
export const ADD_PRESET = 'ADD_PRESET';
export const DELETE_PRESET = 'DELETE_PRESET';
export const RENAME_PRESET = 'RENAME_PRESET';
export const MOVEUP_PRESET = 'MOVEUP_PRESET';
export const MOVEDOWN_PRESET = 'MOVEDOWN_PRESET';


 

